// Generated by CoffeeScript 1.10.0
(function() {
  Router.route('/', function() {
    this.render('Home');
  });

  Router.configure({
    layoutTemplate: 'main'
  });

}).call(this);

//# sourceMappingURL=_router_main.js.map
