// Generated by CoffeeScript 1.10.0
(function() {
  Template.hello.onCreated(function() {
    this.counter = new ReactiveVar(0);
  });

  Template.hello.helpers({
    counter: function() {}
  });

  Template.instance().counter.get();

  Template.hello.events({
    'click button': function(event, instance) {
      instance.counter.set(instance.counter.get() + 1);
    }
  });

}).call(this);

//# sourceMappingURL=main.js.map
