// Generated by CoffeeScript 1.10.0
(function() {
  var projected, random, result;

  this.Shipments = new Mongo.Collection("shipments");

  Shipments.allow({
    insert: function() {
      return true;
    },
    update: function() {
      return true;
    }
  });

  Router.route('/register', {
    template: 'register'
  });

  Router.configure({
    layoutTemplate: 'main'
  });

  Router.route('/', {
    template: 'home',
    name: 'home'
  });

  result = Shipments.find().fetch();

  _.mixin({
    pluckMany: function() {
      var args;
      args = _.rest(arguments, 1);
      return _.map(arguments[0], function(item) {
        var obj;
        obj = {};
        _.each(args, function(arg) {
          obj[arg] = item[arg];
        });
        return obj;
      });
    }
  });

  projected = _.chain(result).pluckMany('date', 'cost').value();

  console.log(JSON.stringify(projected));

  Template.home.rendered = function() {
    var shipment_costs;
    shipment_costs = _.pluck(result, 'cost');
    Tracker.autorun(function() {});
    return $(function() {
      $('#shipment_count').highcharts({
        title: {
          text: 'Shipment Cost Over Time',
          x: -20
        },
        subtitle: {
          text: '',
          x: -20
        },
        xAxis: [
          {
            type: 'datetime',
            minTickInterval: 24 * 3600 * 1000
          }, {
            type: "datetime",
            opposite: true,
            minTickInterval: 24 * 3600 * 1000
          }
        ],
        yAxis: {
          labels: {
            format: '${value}'
          },
          title: {
            text: 'Dollars'
          },
          plotLines: [
            {
              value: 0,
              width: 1,
              color: '#808080'
            }
          ]
        },
        legend: {
          layout: 'vertical',
          align: 'right',
          verticalAlign: 'middle',
          borderWidth: 0
        },
        series: [
          {
            name: 'Shipments'
          }
        ]
      });
    });
  };

  console.log('Hello world');

  console.log('Hello client');

  random = 0.5;

}).call(this);

//# sourceMappingURL=shipment_graph.js.map
