// Generated by CoffeeScript 1.10.0
(function() {
  var random;

  this.Shipments = new Meteor.Collection("shipments");

  Shipments.allow({
    insert: function() {
      return true;
    },
    update: function() {
      return true;
    }
  });

  Router.route('/register', {
    template: 'register'
  });

  Router.configure({
    layoutTemplate: 'main'
  });

  Router.route('/', {
    template: 'home',
    name: 'home'
  });

  Template.home.helpers({
    chart_data_array: function() {
      var chart_data, chart_data_array, i, len, shipment, shipments;
      shipments = Shipments.find({}, {
        sort: {
          'date': 1
        }
      }).fetch();
      chart_data_array = [];
      for (i = 0, len = shipments.length; i < len; i++) {
        shipment = shipments[i];
        chart_data = {};
        chart_data.date = shipment.date;
        console.log(chart_data.date);
        chart_data.cost = shipment.cost;
        chart_data_array.push(chart_data);
      }
      console.log("chart_data_array " + chart_data_array);
      return chart_data_array;
    }
  });

  Template.main.onCreated(function() {
    this.subscribe('shipments');
    return console.log("subscribed");
  });

  Template.home.rendered = function() {
    var data_array;
    data_array = [[Date.UTC(1970, 9, 21), 320], [Date.UTC(1970, 10, 4), 17], [Date.UTC(1970, 10, 9), 225], [Date.UTC(1970, 10, 27), 302], [Date.UTC(1970, 11, 2), 28], [Date.UTC(1970, 11, 16), 428], [Date.UTC(1970, 11, 29), 47], [Date.UTC(1971, 0, 11), 79], [Date.UTC(1971, 0, 26), 172], [Date.UTC(1971, 1, 3), 102], [Date.UTC(1971, 1, 11), 212]];
    return Tracker.autorun(function() {
      $(function() {
        var chart_data, chart_data_array, i, len, shipment, shipments;
        $('#container').highcharts({
          chart: {
            type: 'line'
          },
          title: {
            text: 'Shipments'
          },
          subtitle: {
            text: 'Shipment Cost Over Time'
          },
          xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: {
              month: '%e. %b',
              year: '%b'
            },
            title: {
              text: 'Date'
            }
          },
          yAxis: {
            title: {
              text: 'Cost ($)'
            },
            min: 0
          },
          tooltip: {
            headerFormat: '<b>{series.name}</b><br>',
            pointFormat: '{point.x:%e. %b}: ${point.y:.2f}'
          },
          plotOptions: {
            spline: {
              marker: {
                enabled: true
              }
            }
          },
          series: [
            {
              name: '2015-2016',
              data: data_array
            }
          ]
        });
        shipments = Shipments.find().fetch();
        chart_data_array = [];
        for (i = 0, len = shipments.length; i < len; i++) {
          shipment = shipments[i];
          chart_data = {};
          chart_data.date = shipment.date;
          console.log(chart_data.date);
          chart_data.cost = shipment.cost;
          chart_data_array.push(chart_data);
        }
        return console.log("chart_data_array " + chart_data_array);
      });
    });
  };

  console.log('Hello world');

  random = 0.5;

}).call(this);

//# sourceMappingURL=shipment_graph.js.map
