// Generated by CoffeeScript 1.10.0
(function() {
  this.Shipments = new Mongo.Collection("shipments");

  Shipments.allow({
    insert: function() {
      return true;
    },
    update: function() {
      return true;
    }
  });

}).call(this);

//# sourceMappingURL=shipment_graph.js.map
